# Generated by Django 2.2.1 on 2019-05-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190515_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bartender',
            new_name='Bartenders',
        ),
    ]
