# Generated by Django 2.2.1 on 2019-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190516_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_de_orden',
            name='date_detalleOrden',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
