# Generated by Django 2.2.1 on 2019-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190516_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='bares',
            name='bar_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
