# Generated by Django 2.2.1 on 2019-05-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bares_bar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='product_id',
        ),
        migrations.AddField(
            model_name='detalle_de_orden',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Productos'),
        ),
    ]
